nginx:
    build: ./nginx
    ports:
        - "8080:8080"
        - "8082:8082"
        - "8083:8083"
    links:
        - "php"
    volumes:
        - ~/opt:/opt
                                   
php:
    build: ./php
    ports:
        - "9000:9000"
    links:
        - "mysql"
    volumes:
        - ~/opt:/opt
       
mysql:
    build: ./mysql
    ports:
        - "3306:3306"
    volumes:
        - /home/docker/opt/data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
